# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_project_msgs/Sensors.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sensors(genpy.Message):
  _md5sum = "4fb8452640ac8fb23177d835e52d73c4"
  _type = "my_project_msgs/Sensors"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 encoder_eixo
float64 encoder_as5600_R
float64 encoder_as5600_L"""
  __slots__ = ['encoder_eixo','encoder_as5600_R','encoder_as5600_L']
  _slot_types = ['float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       encoder_eixo,encoder_as5600_R,encoder_as5600_L

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sensors, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.encoder_eixo is None:
        self.encoder_eixo = 0.
      if self.encoder_as5600_R is None:
        self.encoder_as5600_R = 0.
      if self.encoder_as5600_L is None:
        self.encoder_as5600_L = 0.
    else:
      self.encoder_eixo = 0.
      self.encoder_as5600_R = 0.
      self.encoder_as5600_L = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.encoder_eixo, _x.encoder_as5600_R, _x.encoder_as5600_L))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.encoder_eixo, _x.encoder_as5600_R, _x.encoder_as5600_L,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.encoder_eixo, _x.encoder_as5600_R, _x.encoder_as5600_L))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.encoder_eixo, _x.encoder_as5600_R, _x.encoder_as5600_L,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
