# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_project_msgs/TasksGantt.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import my_project_msgs.msg

class TasksGantt(genpy.Message):
  _md5sum = "5262c66c69965c8531fa37eba78e2a23"
  _type = "my_project_msgs/TasksGantt"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """my_project_msgs/TaskState[] task_states
float32 wcet_sensor_read
float32 wcet_publish_ros
float32 wcet_motor_control
float32 wcet_send_gantt
================================================================================
MSG: my_project_msgs/TaskState
int32 task_index
int32 state     
uint32 timestamp

"""
  __slots__ = ['task_states','wcet_sensor_read','wcet_publish_ros','wcet_motor_control','wcet_send_gantt']
  _slot_types = ['my_project_msgs/TaskState[]','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task_states,wcet_sensor_read,wcet_publish_ros,wcet_motor_control,wcet_send_gantt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TasksGantt, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.task_states is None:
        self.task_states = []
      if self.wcet_sensor_read is None:
        self.wcet_sensor_read = 0.
      if self.wcet_publish_ros is None:
        self.wcet_publish_ros = 0.
      if self.wcet_motor_control is None:
        self.wcet_motor_control = 0.
      if self.wcet_send_gantt is None:
        self.wcet_send_gantt = 0.
    else:
      self.task_states = []
      self.wcet_sensor_read = 0.
      self.wcet_publish_ros = 0.
      self.wcet_motor_control = 0.
      self.wcet_send_gantt = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.task_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.task_states:
        _x = val1
        buff.write(_get_struct_2iI().pack(_x.task_index, _x.state, _x.timestamp))
      _x = self
      buff.write(_get_struct_4f().pack(_x.wcet_sensor_read, _x.wcet_publish_ros, _x.wcet_motor_control, _x.wcet_send_gantt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.task_states is None:
        self.task_states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.task_states = []
      for i in range(0, length):
        val1 = my_project_msgs.msg.TaskState()
        _x = val1
        start = end
        end += 12
        (_x.task_index, _x.state, _x.timestamp,) = _get_struct_2iI().unpack(str[start:end])
        self.task_states.append(val1)
      _x = self
      start = end
      end += 16
      (_x.wcet_sensor_read, _x.wcet_publish_ros, _x.wcet_motor_control, _x.wcet_send_gantt,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.task_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.task_states:
        _x = val1
        buff.write(_get_struct_2iI().pack(_x.task_index, _x.state, _x.timestamp))
      _x = self
      buff.write(_get_struct_4f().pack(_x.wcet_sensor_read, _x.wcet_publish_ros, _x.wcet_motor_control, _x.wcet_send_gantt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.task_states is None:
        self.task_states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.task_states = []
      for i in range(0, length):
        val1 = my_project_msgs.msg.TaskState()
        _x = val1
        start = end
        end += 12
        (_x.task_index, _x.state, _x.timestamp,) = _get_struct_2iI().unpack(str[start:end])
        self.task_states.append(val1)
      _x = self
      start = end
      end += 16
      (_x.wcet_sensor_read, _x.wcet_publish_ros, _x.wcet_motor_control, _x.wcet_send_gantt,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2iI = None
def _get_struct_2iI():
    global _struct_2iI
    if _struct_2iI is None:
        _struct_2iI = struct.Struct("<2iI")
    return _struct_2iI
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
