// Generated by gencpp from file my_project_msgs/Command_ackermann.msg
// DO NOT EDIT!


#ifndef MY_PROJECT_MSGS_MESSAGE_COMMAND_ACKERMANN_H
#define MY_PROJECT_MSGS_MESSAGE_COMMAND_ACKERMANN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_project_msgs
{
template <class ContainerAllocator>
struct Command_ackermann_
{
  typedef Command_ackermann_<ContainerAllocator> Type;

  Command_ackermann_()
    : rpm(0.0)
    , servo_angle(0.0)  {
    }
  Command_ackermann_(const ContainerAllocator& _alloc)
    : rpm(0.0)
    , servo_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _rpm_type;
  _rpm_type rpm;

   typedef double _servo_angle_type;
  _servo_angle_type servo_angle;





  typedef boost::shared_ptr< ::my_project_msgs::Command_ackermann_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_project_msgs::Command_ackermann_<ContainerAllocator> const> ConstPtr;

}; // struct Command_ackermann_

typedef ::my_project_msgs::Command_ackermann_<std::allocator<void> > Command_ackermann;

typedef boost::shared_ptr< ::my_project_msgs::Command_ackermann > Command_ackermannPtr;
typedef boost::shared_ptr< ::my_project_msgs::Command_ackermann const> Command_ackermannConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_project_msgs::Command_ackermann_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_project_msgs::Command_ackermann_<ContainerAllocator1> & lhs, const ::my_project_msgs::Command_ackermann_<ContainerAllocator2> & rhs)
{
  return lhs.rpm == rhs.rpm &&
    lhs.servo_angle == rhs.servo_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_project_msgs::Command_ackermann_<ContainerAllocator1> & lhs, const ::my_project_msgs::Command_ackermann_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_project_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::Command_ackermann_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::Command_ackermann_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::Command_ackermann_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26bc2f4c90960827d45039181ffa5114";
  }

  static const char* value(const ::my_project_msgs::Command_ackermann_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26bc2f4c90960827ULL;
  static const uint64_t static_value2 = 0xd45039181ffa5114ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_project_msgs/Command_ackermann";
  }

  static const char* value(const ::my_project_msgs::Command_ackermann_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rpm\n"
"float64 servo_angle\n"
;
  }

  static const char* value(const ::my_project_msgs::Command_ackermann_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rpm);
      stream.next(m.servo_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_ackermann_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_project_msgs::Command_ackermann_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_project_msgs::Command_ackermann_<ContainerAllocator>& v)
  {
    s << indent << "rpm: ";
    Printer<double>::stream(s, indent + "  ", v.rpm);
    s << indent << "servo_angle: ";
    Printer<double>::stream(s, indent + "  ", v.servo_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PROJECT_MSGS_MESSAGE_COMMAND_ACKERMANN_H
