// Generated by gencpp from file my_project_msgs/Sensors.msg
// DO NOT EDIT!


#ifndef MY_PROJECT_MSGS_MESSAGE_SENSORS_H
#define MY_PROJECT_MSGS_MESSAGE_SENSORS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_project_msgs
{
template <class ContainerAllocator>
struct Sensors_
{
  typedef Sensors_<ContainerAllocator> Type;

  Sensors_()
    : encoder_eixo(0.0)
    , encoder_as5600_R(0.0)
    , encoder_as5600_L(0.0)
    , angularVelocity(0.0)  {
    }
  Sensors_(const ContainerAllocator& _alloc)
    : encoder_eixo(0.0)
    , encoder_as5600_R(0.0)
    , encoder_as5600_L(0.0)
    , angularVelocity(0.0)  {
  (void)_alloc;
    }



   typedef double _encoder_eixo_type;
  _encoder_eixo_type encoder_eixo;

   typedef double _encoder_as5600_R_type;
  _encoder_as5600_R_type encoder_as5600_R;

   typedef double _encoder_as5600_L_type;
  _encoder_as5600_L_type encoder_as5600_L;

   typedef double _angularVelocity_type;
  _angularVelocity_type angularVelocity;





  typedef boost::shared_ptr< ::my_project_msgs::Sensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_project_msgs::Sensors_<ContainerAllocator> const> ConstPtr;

}; // struct Sensors_

typedef ::my_project_msgs::Sensors_<std::allocator<void> > Sensors;

typedef boost::shared_ptr< ::my_project_msgs::Sensors > SensorsPtr;
typedef boost::shared_ptr< ::my_project_msgs::Sensors const> SensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_project_msgs::Sensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_project_msgs::Sensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_project_msgs::Sensors_<ContainerAllocator1> & lhs, const ::my_project_msgs::Sensors_<ContainerAllocator2> & rhs)
{
  return lhs.encoder_eixo == rhs.encoder_eixo &&
    lhs.encoder_as5600_R == rhs.encoder_as5600_R &&
    lhs.encoder_as5600_L == rhs.encoder_as5600_L &&
    lhs.angularVelocity == rhs.angularVelocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_project_msgs::Sensors_<ContainerAllocator1> & lhs, const ::my_project_msgs::Sensors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_project_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::Sensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::Sensors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_project_msgs::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62f67af364bf00eab808407950937dc4";
  }

  static const char* value(const ::my_project_msgs::Sensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62f67af364bf00eaULL;
  static const uint64_t static_value2 = 0xb808407950937dc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_project_msgs::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_project_msgs/Sensors";
  }

  static const char* value(const ::my_project_msgs::Sensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_project_msgs::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 encoder_eixo\n"
"float64 encoder_as5600_R\n"
"float64 encoder_as5600_L\n"
"float64 angularVelocity\n"
;
  }

  static const char* value(const ::my_project_msgs::Sensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_project_msgs::Sensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder_eixo);
      stream.next(m.encoder_as5600_R);
      stream.next(m.encoder_as5600_L);
      stream.next(m.angularVelocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_project_msgs::Sensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_project_msgs::Sensors_<ContainerAllocator>& v)
  {
    s << indent << "encoder_eixo: ";
    Printer<double>::stream(s, indent + "  ", v.encoder_eixo);
    s << indent << "encoder_as5600_R: ";
    Printer<double>::stream(s, indent + "  ", v.encoder_as5600_R);
    s << indent << "encoder_as5600_L: ";
    Printer<double>::stream(s, indent + "  ", v.encoder_as5600_L);
    s << indent << "angularVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.angularVelocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PROJECT_MSGS_MESSAGE_SENSORS_H
