// Generated by gencpp from file my_project_msgs/TasksSchedule.msg
// DO NOT EDIT!


#ifndef MY_PROJECT_MSGS_MESSAGE_TASKSSCHEDULE_H
#define MY_PROJECT_MSGS_MESSAGE_TASKSSCHEDULE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_project_msgs
{
template <class ContainerAllocator>
struct TasksSchedule_
{
  typedef TasksSchedule_<ContainerAllocator> Type;

  TasksSchedule_()
    : task_sensor()
    , task_motor_control()
    , task_publish()
    , task_scheduler()  {
    }
  TasksSchedule_(const ContainerAllocator& _alloc)
    : task_sensor(_alloc)
    , task_motor_control(_alloc)
    , task_publish(_alloc)
    , task_scheduler(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_sensor_type;
  _task_sensor_type task_sensor;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_motor_control_type;
  _task_motor_control_type task_motor_control;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_publish_type;
  _task_publish_type task_publish;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_scheduler_type;
  _task_scheduler_type task_scheduler;





  typedef boost::shared_ptr< ::my_project_msgs::TasksSchedule_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_project_msgs::TasksSchedule_<ContainerAllocator> const> ConstPtr;

}; // struct TasksSchedule_

typedef ::my_project_msgs::TasksSchedule_<std::allocator<void> > TasksSchedule;

typedef boost::shared_ptr< ::my_project_msgs::TasksSchedule > TasksSchedulePtr;
typedef boost::shared_ptr< ::my_project_msgs::TasksSchedule const> TasksScheduleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_project_msgs::TasksSchedule_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_project_msgs::TasksSchedule_<ContainerAllocator1> & lhs, const ::my_project_msgs::TasksSchedule_<ContainerAllocator2> & rhs)
{
  return lhs.task_sensor == rhs.task_sensor &&
    lhs.task_motor_control == rhs.task_motor_control &&
    lhs.task_publish == rhs.task_publish &&
    lhs.task_scheduler == rhs.task_scheduler;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_project_msgs::TasksSchedule_<ContainerAllocator1> & lhs, const ::my_project_msgs::TasksSchedule_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_project_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::TasksSchedule_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::TasksSchedule_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::TasksSchedule_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f7390576d604b72feca1119d3cd344a";
  }

  static const char* value(const ::my_project_msgs::TasksSchedule_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f7390576d604b72ULL;
  static const uint64_t static_value2 = 0xfeca1119d3cd344aULL;
};

template<class ContainerAllocator>
struct DataType< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_project_msgs/TasksSchedule";
  }

  static const char* value(const ::my_project_msgs::TasksSchedule_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task_sensor\n"
"string task_motor_control\n"
"string task_publish\n"
"string task_scheduler\n"
;
  }

  static const char* value(const ::my_project_msgs::TasksSchedule_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_sensor);
      stream.next(m.task_motor_control);
      stream.next(m.task_publish);
      stream.next(m.task_scheduler);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TasksSchedule_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_project_msgs::TasksSchedule_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_project_msgs::TasksSchedule_<ContainerAllocator>& v)
  {
    s << indent << "task_sensor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_sensor);
    s << indent << "task_motor_control: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_motor_control);
    s << indent << "task_publish: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_publish);
    s << indent << "task_scheduler: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_scheduler);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PROJECT_MSGS_MESSAGE_TASKSSCHEDULE_H
