// Generated by gencpp from file my_project_msgs/TasksGantt.msg
// DO NOT EDIT!


#ifndef MY_PROJECT_MSGS_MESSAGE_TASKSGANTT_H
#define MY_PROJECT_MSGS_MESSAGE_TASKSGANTT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_project_msgs/TaskState.h>

namespace my_project_msgs
{
template <class ContainerAllocator>
struct TasksGantt_
{
  typedef TasksGantt_<ContainerAllocator> Type;

  TasksGantt_()
    : task_states()
    , wcet_sensor_read(0.0)
    , wcet_publish_ros(0.0)
    , wcet_motor_control(0.0)
    , wcet_send_gantt(0.0)  {
    }
  TasksGantt_(const ContainerAllocator& _alloc)
    : task_states(_alloc)
    , wcet_sensor_read(0.0)
    , wcet_publish_ros(0.0)
    , wcet_motor_control(0.0)
    , wcet_send_gantt(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::my_project_msgs::TaskState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::my_project_msgs::TaskState_<ContainerAllocator> >> _task_states_type;
  _task_states_type task_states;

   typedef float _wcet_sensor_read_type;
  _wcet_sensor_read_type wcet_sensor_read;

   typedef float _wcet_publish_ros_type;
  _wcet_publish_ros_type wcet_publish_ros;

   typedef float _wcet_motor_control_type;
  _wcet_motor_control_type wcet_motor_control;

   typedef float _wcet_send_gantt_type;
  _wcet_send_gantt_type wcet_send_gantt;





  typedef boost::shared_ptr< ::my_project_msgs::TasksGantt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_project_msgs::TasksGantt_<ContainerAllocator> const> ConstPtr;

}; // struct TasksGantt_

typedef ::my_project_msgs::TasksGantt_<std::allocator<void> > TasksGantt;

typedef boost::shared_ptr< ::my_project_msgs::TasksGantt > TasksGanttPtr;
typedef boost::shared_ptr< ::my_project_msgs::TasksGantt const> TasksGanttConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_project_msgs::TasksGantt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_project_msgs::TasksGantt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_project_msgs::TasksGantt_<ContainerAllocator1> & lhs, const ::my_project_msgs::TasksGantt_<ContainerAllocator2> & rhs)
{
  return lhs.task_states == rhs.task_states &&
    lhs.wcet_sensor_read == rhs.wcet_sensor_read &&
    lhs.wcet_publish_ros == rhs.wcet_publish_ros &&
    lhs.wcet_motor_control == rhs.wcet_motor_control &&
    lhs.wcet_send_gantt == rhs.wcet_send_gantt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_project_msgs::TasksGantt_<ContainerAllocator1> & lhs, const ::my_project_msgs::TasksGantt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_project_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::TasksGantt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::TasksGantt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::TasksGantt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5262c66c69965c8531fa37eba78e2a23";
  }

  static const char* value(const ::my_project_msgs::TasksGantt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5262c66c69965c85ULL;
  static const uint64_t static_value2 = 0x31fa37eba78e2a23ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_project_msgs/TasksGantt";
  }

  static const char* value(const ::my_project_msgs::TasksGantt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_project_msgs/TaskState[] task_states\n"
"float32 wcet_sensor_read\n"
"float32 wcet_publish_ros\n"
"float32 wcet_motor_control\n"
"float32 wcet_send_gantt\n"
"================================================================================\n"
"MSG: my_project_msgs/TaskState\n"
"int32 task_index\n"
"int32 state     \n"
"uint32 timestamp\n"
"\n"
;
  }

  static const char* value(const ::my_project_msgs::TasksGantt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_states);
      stream.next(m.wcet_sensor_read);
      stream.next(m.wcet_publish_ros);
      stream.next(m.wcet_motor_control);
      stream.next(m.wcet_send_gantt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TasksGantt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_project_msgs::TasksGantt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_project_msgs::TasksGantt_<ContainerAllocator>& v)
  {
    s << indent << "task_states[]" << std::endl;
    for (size_t i = 0; i < v.task_states.size(); ++i)
    {
      s << indent << "  task_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::my_project_msgs::TaskState_<ContainerAllocator> >::stream(s, indent + "    ", v.task_states[i]);
    }
    s << indent << "wcet_sensor_read: ";
    Printer<float>::stream(s, indent + "  ", v.wcet_sensor_read);
    s << indent << "wcet_publish_ros: ";
    Printer<float>::stream(s, indent + "  ", v.wcet_publish_ros);
    s << indent << "wcet_motor_control: ";
    Printer<float>::stream(s, indent + "  ", v.wcet_motor_control);
    s << indent << "wcet_send_gantt: ";
    Printer<float>::stream(s, indent + "  ", v.wcet_send_gantt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PROJECT_MSGS_MESSAGE_TASKSGANTT_H
