// Generated by gencpp from file my_project_msgs/TaskState.msg
// DO NOT EDIT!


#ifndef MY_PROJECT_MSGS_MESSAGE_TASKSTATE_H
#define MY_PROJECT_MSGS_MESSAGE_TASKSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_project_msgs
{
template <class ContainerAllocator>
struct TaskState_
{
  typedef TaskState_<ContainerAllocator> Type;

  TaskState_()
    : task_index(0)
    , state(0)
    , timestamp(0)  {
    }
  TaskState_(const ContainerAllocator& _alloc)
    : task_index(0)
    , state(0)
    , timestamp(0)  {
  (void)_alloc;
    }



   typedef int32_t _task_index_type;
  _task_index_type task_index;

   typedef int32_t _state_type;
  _state_type state;

   typedef uint32_t _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::my_project_msgs::TaskState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_project_msgs::TaskState_<ContainerAllocator> const> ConstPtr;

}; // struct TaskState_

typedef ::my_project_msgs::TaskState_<std::allocator<void> > TaskState;

typedef boost::shared_ptr< ::my_project_msgs::TaskState > TaskStatePtr;
typedef boost::shared_ptr< ::my_project_msgs::TaskState const> TaskStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_project_msgs::TaskState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_project_msgs::TaskState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_project_msgs::TaskState_<ContainerAllocator1> & lhs, const ::my_project_msgs::TaskState_<ContainerAllocator2> & rhs)
{
  return lhs.task_index == rhs.task_index &&
    lhs.state == rhs.state &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_project_msgs::TaskState_<ContainerAllocator1> & lhs, const ::my_project_msgs::TaskState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_project_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::TaskState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_project_msgs::TaskState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::TaskState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msgs::TaskState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::TaskState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msgs::TaskState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_project_msgs::TaskState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9b75f49a4033f347da6f7f095be60f2";
  }

  static const char* value(const ::my_project_msgs::TaskState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9b75f49a4033f34ULL;
  static const uint64_t static_value2 = 0x7da6f7f095be60f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_project_msgs::TaskState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_project_msgs/TaskState";
  }

  static const char* value(const ::my_project_msgs::TaskState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_project_msgs::TaskState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 task_index\n"
"int32 state     \n"
"uint32 timestamp\n"
"\n"
;
  }

  static const char* value(const ::my_project_msgs::TaskState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_project_msgs::TaskState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_index);
      stream.next(m.state);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_project_msgs::TaskState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_project_msgs::TaskState_<ContainerAllocator>& v)
  {
    s << indent << "task_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_index);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
    s << indent << "timestamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PROJECT_MSGS_MESSAGE_TASKSTATE_H
