# Car parameters
wheelBase: 0.248
wheelRadius: 0.0335

# Parameters actuators
offset_angle_servo: 89
min_angle_servo: -20
max_angle_servo: 20
max_speed: 0.45

# Gain controllers
# para 0,3 mm/s
# K_1: -30.3491
# K_2: -9.4208

# para 0,45 mm/s
# K_1: -13.9923  
# K_2: -6.2294

K_1: -14.8101 
K_2: -4.9793

# k_1: -22.1627
# K_2: -5.7312

# Parameters path
A: -0.5774
B: 1
C: 0