# Car parameters
wheelBase: 0.248
wheelRadius: 0.0335

# Parameters actuators
offset_angle_servo: 92
min_angle_servo: -27
max_angle_servo: 27
max_speed: 0.45

# Gain controllers
# para 0,3 mm/s
k_1: -4.095
K_2: -7.8182

# Parameters path
A: -0.5774
B: 1
C: 0