# Car parameters
wheelBase: 0.248
wheelRadius: 0.0335

# Parameters actuators
offset_angle_servo: 92
min_angle_servo: -27
max_angle_servo: 27
max_speed: 0.45

# Gain controllers
# H-infinito

# k_1: -226.2121
# K_2: -15.0031

# funcional
K_1: -14.0055   
K_2: -6.2

# Parameters path
A: -0.5774
B: 1
C: 0